server:
  port: 8081
eureka:  client:    register-with-eureka: true
    service-url:      default: ${EUREKA_URI:http://localhost:8761/eureka} 
spring:  application:    name: swiggy-service
      