
package com.hdfc.netbanking.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.hdfc.netbanking.types.Account;
import com.hdfc.netbanking.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "AccountDetailsEndpoint", targetNamespace = "http://www.hdfc.com/netbanking/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface AccountDetailsEndpoint {


    /**
     *
     * @param in
     * @return
     *     returns com.hdfc.netbanking.types.Account
     */
    @WebMethod(action = "http://www.hdfc.com/netbanking/services/getAccount")
    @WebResult(name = "account", targetNamespace = "http://www.hdfc.com/netbanking/types", partName = "out")
    public Account getAccount(@WebParam(name = "accountNo", targetNamespace = "http://www.hdfc.com/netbanking/types",
                                        partName = "in") String in);

}












