package com.hdfc.netbanking.services;

import com.hdfc.netbanking.types.Account;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class AccountDetailsEndpointSOAP12PortClient {
    public static void main(String[] args) {
        AccountDetailsEndpointService accountDetailsEndpointService = new AccountDetailsEndpointService();
        AccountDetailsEndpoint accountDetailsEndpoint =
            accountDetailsEndpointService.getAccountDetailsEndpointSOAP12Port();
       Account account = accountDetailsEndpoint.getAccount("a9393");
       System.out.println("Account Holder Name :" + account.getAccountHolderName());


    }
}
