package com.hdfc.netbanking.services;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class AccountDetailsEndpointSOAP11PortClient {
    public static void main(String[] args) {
        AccountDetailsEndpointService accountDetailsEndpointService = new AccountDetailsEndpointService();
        AccountDetailsEndpoint accountDetailsEndpoint =
            accountDetailsEndpointService.getAccountDetailsEndpointSOAP11Port();
        // Add your code to call the desired methods.


    }
}
