
package in.airtel.recharge.service;

import javax.xml.ws.WebFault;
import in.airtel.recharge.types.Cause;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "cause", targetNamespace = "http://www.airtel.in/recharge/types")
public class MobileNotValidFault extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private Cause faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public MobileNotValidFault(String message, Cause faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public MobileNotValidFault(String message, Cause faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: in.airtel.recharge.types.Cause
	 */
	public Cause getFaultInfo() {
		return faultInfo;
	}

}
