spring:
  profiles:    active:    - stage
---
spring:  profiles:  - dev
db:
  driverClassname: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db
  username: root
  password: root
---
spring:
  profiles:
  - stage
db:
  driverClassname: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin@localhost:1521:xe
  username: root
  password: welcome1
  
  
  
  
  
  
  
  
  
  
  
  