
package in.airtel.recharge.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RechargeGatewayPartnerImplService", targetNamespace = "http://service.recharge.airtel.in/", wsdlLocation = "http://localhost:8081/RechargeBus/recharge?wsdl")
public class RechargeGatewayPartnerImplService
    extends Service
{

    private final static URL RECHARGEGATEWAYPARTNERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECHARGEGATEWAYPARTNERIMPLSERVICE_EXCEPTION;
    private final static QName RECHARGEGATEWAYPARTNERIMPLSERVICE_QNAME = new QName("http://service.recharge.airtel.in/", "RechargeGatewayPartnerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/RechargeBus/recharge?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECHARGEGATEWAYPARTNERIMPLSERVICE_WSDL_LOCATION = url;
        RECHARGEGATEWAYPARTNERIMPLSERVICE_EXCEPTION = e;
    }

    public RechargeGatewayPartnerImplService() {
        super(__getWsdlLocation(), RECHARGEGATEWAYPARTNERIMPLSERVICE_QNAME);
    }

    public RechargeGatewayPartnerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECHARGEGATEWAYPARTNERIMPLSERVICE_QNAME, features);
    }

    public RechargeGatewayPartnerImplService(URL wsdlLocation) {
        super(wsdlLocation, RECHARGEGATEWAYPARTNERIMPLSERVICE_QNAME);
    }

    public RechargeGatewayPartnerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECHARGEGATEWAYPARTNERIMPLSERVICE_QNAME, features);
    }

    public RechargeGatewayPartnerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RechargeGatewayPartnerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RechargeGatewayPartner
     */
    @WebEndpoint(name = "RechargeGatewayPartnerImplPort")
    public RechargeGatewayPartner getRechargeGatewayPartnerImplPort() {
        return super.getPort(new QName("http://service.recharge.airtel.in/", "RechargeGatewayPartnerImplPort"), RechargeGatewayPartner.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RechargeGatewayPartner
     */
    @WebEndpoint(name = "RechargeGatewayPartnerImplPort")
    public RechargeGatewayPartner getRechargeGatewayPartnerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.recharge.airtel.in/", "RechargeGatewayPartnerImplPort"), RechargeGatewayPartner.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECHARGEGATEWAYPARTNERIMPLSERVICE_EXCEPTION!= null) {
            throw RECHARGEGATEWAYPARTNERIMPLSERVICE_EXCEPTION;
        }
        return RECHARGEGATEWAYPARTNERIMPLSERVICE_WSDL_LOCATION;
    }

}
