
package in.airtel.recharge.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import in.airtel.recharge.types.ObjectFactory;
import in.airtel.recharge.types.Receipt;
import in.airtel.recharge.types.Topup;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RechargeGatewayPartner", targetNamespace = "http://www.airtel.in/recharge/service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RechargeGatewayPartner {


    /**
     * 
     * @param in
     * @return
     *     returns in.airtel.recharge.types.Receipt
     */
    @WebMethod(action = "http://www.airtel.in/recharge/service/recharge")
    @WebResult(name = "receipt", targetNamespace = "http://www.airtel.in/recharge/types", partName = "out")
    @Action(input = "http://www.airtel.in/recharge/service/recharge", output = "http://www.airtel.in/recharge/service/RechargeGatewayPartner/rechargeResponse")
    public Receipt recharge(
        @WebParam(name = "topup", targetNamespace = "http://www.airtel.in/recharge/types", partName = "in")
        Topup in);

}
