
package com.axisbank.netbanking.services;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2019-10-23T10:07:01.330+05:30
 * Generated source version: 2.6.9
 * 
 */
 
public class Netbanking_NetbankingSOAPPort_Server{

    protected Netbanking_NetbankingSOAPPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new NetbankingImpl();
        String address = "http://www.example.org/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Netbanking_NetbankingSOAPPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
