
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.axisbank.netbanking.services;

import java.util.UUID;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.axisbank.netbanking.types.Receipt;

/**
 * This class was generated by Apache CXF 2.6.9 2019-10-23T10:07:01.287+05:30
 * Generated source version: 2.6.9
 * 
 */

@javax.jws.WebService(serviceName = "netbankingService", portName = "netbankingSOAPPort", targetNamespace = "http://www.axisbank.com/netbanking/services", wsdlLocation = "/WEB-INF/netbanking.wsdl", endpointInterface = "com.axisbank.netbanking.services.Netbanking")

public class NetbankingImpl implements Netbanking {

	private static final Logger LOG = Logger.getLogger(NetbankingImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.axisbank.netbanking.services.Netbanking#withdrawl(com.axisbank.netbanking
	 * .types.WithdrawlInfo in )*
	 */
	public com.axisbank.netbanking.types.Receipt withdrawl(com.axisbank.netbanking.types.WithdrawlInfo in) {
		LOG.info("Executing operation withdrawl");
		System.out.println(in);
		try {
			com.axisbank.netbanking.types.Receipt receipt = null;
			receipt = new Receipt();

			receipt.setReferenceNo(UUID.randomUUID().toString());
			receipt.setStatus("Success");

			return receipt;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
