//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.15 at 07:49:53 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sparkframework.org/web/config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sparkframework.web.config;
